### ISSUE TITLE
Ugly exception when wallet has insufficient funds to deploy smart-contract

### ISSUE THREAD

**Issue by thibauld** [C-ORG/c-org#1]
When I try to deploy a CO with a wallet that has insufficient funds, I get a very ugly exception. It would nice to catch it and display something like:
` the specified wallet has insufficient funds to deploy your Continuous Organization, please send ~0.1eth to <address>`

![image](https://user-images.githubusercontent.com/197119/44936907-a86e9180-ad44-11e8-9650-5d9fc514aa0b.png)

**Comment by guhur** [comment]
Fix on commit https://github.com/C-ORG/c-org/commit/67b707008c1bc18e008294a10296b45ef4631470 
Thanks for the report!
